# ────────────────────────────────────────────────────────────
# Custom Theme for Kitty
# Made with Omarchist
# ────────────────────────────────────────────────────────────

## name: Custom Theme

foreground              #35302a
background              #F5E6D3
selection_foreground    #35302a
selection_background    #c68d95

cursor                  #DEA193
cursor_text_color       #35302a

# URL underline color when hovering with mouse
url_color               #35302a

# Tab bar colors
active_tab_foreground   #35302a
active_tab_background   #F5E6D3
inactive_tab_foreground #35302a
inactive_tab_background #F5E6D3
tab_bar_background      #35302a

color0  #F5E6D3
color8  #C8AC86
color1  #a02b16
color9  #a02b16
color2  #9e4f5b
color10 #9e4f5b
color3  #644535
color11 #694C45
color4  #76634c
color12 #76634c
color5  #9b4d61
color13 #9b4d61
color6  #713a56
color14 #713a56
color7  #a94a34
color15 #a94a34
